%8PSK
clear,clc
N=32;%0,1随机信号的个数
s=randi([0,1],N,1);%产生60个随机信号
s_s=conv_code(s);
r_r=hard_decode(s_s);
subplot(2,2,1)
stem(1:length(s),s)
title('原始序列')
xlabel('时间')
ylabel('码字')
subplot(2,2,2)
stem(1:length(s_s),s_s)
title('卷积编码后的序列')
xlabel('时间')
ylabel('码字')
subplot(2,2,3)
stem(1:length(r_r),r_r)
xlabel('时间')
ylabel('码字')
title('维特比硬判决译码序列')
subplot(2,2,4)
stem(1:length(r_r),r_r)
xlabel('时间')
ylabel('码字')
title('维特比软判决译码序列')