load('matlab.mat')
%%
%原始数据
figure
stem(1:length(data),data)
xlabel('时间')
ylabel('幅度')
%%
%8PSK
figure
subplot(2,1,1)
stem(1:length(modData),real(modData))
title('同相分量')
xlabel('时间')
ylabel('幅度')
subplot(2,1,2)
stem(1:length(modData),imag(modData))
title('正交分量')
xlabel('时间')
ylabel('幅度')
%%
%成型滤波
figure
subplot(2,1,1)
plot(1:length(x_psk),real(x_psk))
title('同相分量')
xlabel('时间')
ylabel('幅度')
subplot(2,1,2)
plot(1:length(x_psk),imag(x_psk))
title('正交分量')
xlabel('时间')
ylabel('幅度')
%%
%发送波形
figure
plot(1:length(x_psk),real(x_psk)+imag(x_psk))
xlabel('时间')
ylabel('幅度')
%发送波形
figure
plot(1:length(rxSig),real(rxSig)+imag(rxSig))
xlabel('时间')
ylabel('幅度')
%%
%匹配滤波
figure
subplot(2,1,1)
plot(1:length(rxSig),real(rxSig))
title('同相分量')
xlabel('时间')
ylabel('幅度')
subplot(2,1,2)
plot(1:length(rxSig),imag(rxSig))
title('正交分量')
xlabel('时间')
ylabel('幅度')
%%
%均衡判决
figure
subplot(2,1,1)
stem(1:length(modData),real(modData))
title('同相分量')
xlabel('时间')
ylabel('幅度')
subplot(2,1,2)
stem(1:length(modData),imag(modData))
title('正交分量')
xlabel('时间')
ylabel('幅度')
%%
%解映射
figure
stem(1:length(data),data)
xlabel('时间')
ylabel('幅度')

